name: Tauri Build (Win/macOS/Linux)

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v1.0.1"

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            linux: true
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf


      - name: Install JS deps
        run: npm ci

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        with:
          args: --ci
        env:
          TAURI_PRIVATE_KEY: ""
          TAURI_KEY_PASSWORD: ""

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: subvision-${{ runner.os }}
          path: |
            src-tauri/target/release/bundle/**/*
          if-no-files-found: error
